services:
  web:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backlink_web
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    env_file:
      - .env
    depends_on:
      - db
      - redis

  celery:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backlink_celery
    command: celery -A app.core.celery_app.celery_app worker --loglevel=info
    volumes:
      - ./backend:/app
    env_file:
      - .env
    depends_on:
      - web
      - redis
      - db

  celery_beat:
      build:
        context: ./backend
        dockerfile: Dockerfile
      container_name: backlink_beat
      command: celery -A app.core.celery_app.celery_app beat --loglevel=info
      volumes:
        - ./backend:/app
      env_file:
        - .env
      depends_on:
        - web
        - redis
        - db
      
  db:
    image: postgres:13
    container_name: backlink_db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: backlinkdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    container_name: backlink_redis
    ports:
      - "6379:6379"

volumes:
  postgres_data:
